<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>侏罗纪世界 磁力链接 - 磁力搜索</title>
<meta name="keywords" content="磁力搜索, 磁力链接, 磁力搜, 磁力链, 磁力链接搜索, btbook" />
<meta name="description" content="侏罗纪世界的磁力链接" />
<meta name="viewport" content="width=device-width" />
<link type="text/css" rel="stylesheet" href="/static/css/default.css" />
<link rel="shortcut icon" type="image/x-icon"
	href="/static/img/favicon.ico" />
<script src="/static/js/default.js" type="text/javascript"></script>
</head>
<body>
	<div id="wrapper">
		<div class="top-bar">
			<span class="first"><a href="/">磁力搜索</a></span> <select
				autocomplete="off" onchange="changeLanguage(this.value)">
				<option value="EN">English</option>
				<option value="KR">한국어</option>
				<option value="JP">日本語</option>
				<option value="TW">繁體中文</option>
				<option value="CN" selected>简体中文</option>
			</select>
		</div>
		<div class="header-div">
			<form class="search-form" action="/search" method="get">
				<a href="/" title="磁力搜索"> <img src="/static/img/logo_40.png"
					alt="磁力搜索" class="nav-logo" />
				</a> <input type="text" id="search" title="Search" value="侏罗纪世界"
					autocomplete="off" name="q" /> <input type="submit" id="btnSearch"
					value="搜 索" class="blue" />
			</form>
			<script type="text/javascript">
                document.getElementById("search").focus();
                document.forms[0].onsubmit = function (e) {
                    e.preventDefault(); var query = document.getElementById("search").value; if (!query) { document.getElementById("search").focus(); return false; }
                    var url = '/search/' + encodeURIComponent(query) + '.html'; window.location = url; return false;
                };
            </script>
		</div>

		<div id="sort-bar">
			<b>创建时间</b> <a
				href="/search/%e4%be%8f%e7%bd%97%e7%ba%aa%e4%b8%96%e7%95%8c/1-2.html">文件大小</a>
			<a
				href="/search/%e4%be%8f%e7%bd%97%e7%ba%aa%e4%b8%96%e7%95%8c/1-3.html">下载热度</a>
			<a
				href="/search/%e4%be%8f%e7%bd%97%e7%ba%aa%e4%b8%96%e7%95%8c/1-4.html">相关度</a>

		</div>

		<div id="content">
			<div id="wall">

				<div class="search-statu">
					<span>大约 50 条结果，耗时 1 毫秒。</span> <span> <a
						href="/rss/%e4%be%8f%e7%bd%97%e7%ba%aa%e4%b8%96%e7%95%8c.xml"
						target="_blank" type="application/rss+xml"> <img
							src="/static/img/icon_rss.gif" alt="rss" />
					</a>
					</span>
				</div>
				<div class="search-item">
					<div class="item-title">
						<h3>
							<a href="/wiki/a8955186cd9509af906dcb293795733e62efed48.html"
								target="_blank">Jurassic.World.2015.<b>侏罗纪世界</b>.720p.Chi_Eng.ZMZ-BD-MP4.mp4
							</a>
						</h3>
					</div>
					<div class="item-list">
						<ul>
							<li>Jurassic.World.2015.侏罗纪世界.720p.Chi_Eng.ZMZ-BD-MP4.mp4 <span
								class="lightColor">1.7 GB</span></li>
						</ul>
					</div>
					<div class="item-bar">
						<span class="cpill fileType1">视频</span> <span> 创建时间： <b>1个月前</b>
						</span><span> 文件大小： <b class="cpill yellow-pill">1.7 GB</b>

						</span> <span>下载热度：<b>1</b></span> <span>最近下载：<b>1个月前</b></span> <a
							href="magnet:?xt=urn:btih:A8955186CD9509AF906DCB293795733E62EFED48"
							class="download">磁力链接</a> <a
							href="thunder://QUFtYWduZXQ6P3h0PXVybjpidGloOkE4OTU1MTg2Q0Q5NTA5QUY5MDZEQ0IyOTM3OTU3MzNFNjJFRkVENDhaWg=="
							class="download">迅雷链接</a>
					</div>
				</div>

				<div class="bottom-pager">
					<span>1</span> <a
						href="/search/%e4%be%8f%e7%bd%97%e7%ba%aa%e4%b8%96%e7%95%8c/2-1.html">2</a>
					<a
						href="/search/%e4%be%8f%e7%bd%97%e7%ba%aa%e4%b8%96%e7%95%8c/3-1.html">3</a>
					<a
						href="/search/%e4%be%8f%e7%bd%97%e7%ba%aa%e4%b8%96%e7%95%8c/4-1.html">4</a>
					<a
						href="/search/%e4%be%8f%e7%bd%97%e7%ba%aa%e4%b8%96%e7%95%8c/5-1.html">5</a>
					<a
						href="/search/%e4%be%8f%e7%bd%97%e7%ba%aa%e4%b8%96%e7%95%8c/2-1.html">
						&gt; </a>
				</div>

				<div class="push"></div>
			</div>
		</div>
	</div>
	<div class="footer">
		<span>©2016 bthave.org</span> <span><a href="/mobile" rel="nofollow">移动版</a>
			| <a href="/online" rel="nofollow">在线播放</a> | <a href="/about"
			rel="nofollow">关于</a></span>
	</div>
</body>
</html>