<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title><?=$req['q'] ?>_中国最大的IT信息搜索引擎</title>
<meta name="keywords" content="中国最大的IT信息搜索引擎" />
<meta name="description" content="中国最大的IT信息搜索引擎" />
<meta name="viewport" content="width=device-width" />
<link type="text/css" rel="stylesheet" href="/static/css/default.css" />
<link rel="shortcut icon" type="image/x-icon" href="/static/img/favicon.ico" />
<script src="/static/js/default.js" type="text/javascript"></script>
<style>
</style>
</head>
<body>
	<div id="wrapper">
		<div class="top-bar">
			<span class="first"><a href="/">首页</a></span> 
			<span><a href="/tags">标签云</a></span> 
			<span><a href="/">视频搜索</a></span> 
			<select autocomplete="off" onchange="changeLanguage(this.value)">
				<option value="CN" selected>简体中文</option>
			</select>
		</div>
		<div class="header-div">
			<form class="search-form" action="/search" method="get" id='s_form'>
				<a href="/" > <img src="/static/img/logo_40.png" class="nav-logo" /> </a> 
				<input type="text" id="search" title="Search" value="<?=$req['q']?>" autocomplete="off" name="q" /> 
				<input type="submit" id="btnSearch" value="搜 索" class="blue" />
			</form>
			<script type="text/javascript">
                document.getElementById("search").focus();
                document.forms[0].onsubmit = function (e) {
                    e.preventDefault(); 
                    var query = document.getElementById("search").value;
                    if (!query) { document.getElementById("search").focus();
                     return false; 
                    }
                    document.getElementById("s_form").submit();
                };
            </script>
		</div>

		<div id="sort-bar" style='display: none;'>
			<b>创建时间</b> <a
				href="/search/%e4%be%8f%e7%bd%97%e7%ba%aa%e4%b8%96%e7%95%8c/1-2.html">文件大小</a>
			<a
				href="/search/%e4%be%8f%e7%bd%97%e7%ba%aa%e4%b8%96%e7%95%8c/1-3.html">下载热度</a>
			<a
				href="/search/%e4%be%8f%e7%bd%97%e7%ba%aa%e4%b8%96%e7%95%8c/1-4.html">相关度</a>
		</div>

		<div id="content">
			<div id="wall">

				<div class="search-statu">
					<span>
					   大约  <?=$sph_res['total_found']?> 条结果，耗时 <?=$sph_res['time']*1000?> 毫秒。
					   &nbsp;已收录 [<?=$crawl_total?>]
					</span> 
					<span> 
					<a style='display: none;' href="" target="_blank" type="application/rss+xml"> 
					   <img src="/static/img/icon_rss.gif" alt="rss" />
					</a>
					</span>
				</div>
				
				<!-- list begin -->
				<?php foreach($page_data as $k=>$v):?>
				<div class="search-item">
					<div class="item-title">
						<h3>
							<a href="<?=$v['link']?>"
								target="_blank"><?=$v['title']?>
							</a>
						</h3>
					</div>
					<div class="item-list">
						<ul>
							<li><?=$v['description']?></li>
						</ul>
					</div>
					<div class="item-bar">
						<span class="cpill fileType1">博客园</span> 
						<span><b> posted @ <?=$v['post_time']?></b>&nbsp;&nbsp; <b><?=$v['post_author']?></b></span>  
						<span> 阅读(<b><?=$v['view_count']?></b>)</span>  
						<span> 评论(<b><?=$v['comment_count']?></b>)</span>  
					</div>
				</div>
				<?php endforeach;?>
				<!-- list end -->

				<!-- page begin -->
				<div class="bottom-pager">
					<?=$page_nav?>
				</div>
				<!-- page end -->

				<div class="push"></div>
			</div>
		</div>
	</div>
	<div class="footer">
		<span>©2016 <a href='http://xiuran.me' target='_blank'>http://xiuran.me</a></span> 
		<span>
			 <a href="javascript:;" rel="nofollow">联系我们</a> 
			| <a href="javascript:;"  rel="nofollow">关于我们</a>
			| <a href="https://github.com/xiaobenxiong/search-web"  rel="nofollow" target='_blank'>源代码</a>
			| <a href="https://github.com/xiaobenxiong/search-crawl"  rel="nofollow" target='_blank'>源代码[爬虫]</a>
		</span>
	</div>
</body>
</html>
