<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>标签云</title>
<link rel="stylesheet"  rel="stylesheet"  type="text/css" href="/static/css/miaov_style.css" />
<script type="text/javascript" src="/static/js/miaov.js"></script>
<link type="text/css" rel="stylesheet" href="/static/css/default.css?v=2.2" />
</head>

<body>
<div class="top-bar" style='background-color:-moz-mac-accentface'>
		<span class="first"><a href="/">首页</a></span> 
		<span><a href="/tags" style="background-color:#4c4c4c">标签云</a></span> 
		<span><a href="/">视频搜索</a></span> 
		<select autocomplete="off" onchange="changeLanguage(this.value)">
			<option value="CN" selected>简体中文</option>
		</select>
</div>
		
<div id="div1">
	<a href="/search?q=微信开发">微信开发</a>
	<a href="/search?q=Bootstarp" class="red">Solr</a>
	<a href="/search?q=Python基础">Python基础</a>
	<a href="/search?q=计算机网络">计算机网络</a>
	<a href="/search?q=数据挖掘" class="blue2">数据挖掘</a>
	<a href="/search?q=kafka">kafka</a>
	<a href="/search?q=Zookeeper" class="red">Docker</a>
	<a href="/search?q=JavaScript" class="yellow">JavaScript</a>
	<a href="/search?q=Yaf">Yaf</a>
	<a href="/search?q=数据分析" class="red">数据分析</a>
	<a href="/search?q=Vanish">Vanish</a>
	<a href="/search?q=HTTP协议详解" class="blue2">HTTP协议详解</a>
	<a href="/search?q=git">Git/SVN</a>
	<a href="/search?q=设计模式" class="red">设计模式</a>
	<a href="/search?q=数据结构" class="blue2">数据结构</a>
	<a href="/search?q=OpenStack">OpenStack</a>
	<a href="/search?q=自动化运维" class="blue2">自动化运维</a>
	<a href="/search?q=Cassandra">Cassandra</a>
	<a href="/search?q=MongoDB">MongoDB</a>
	<a href="/search?q=Redis" class="yellow">Redis</a>
	<a href="/search?q=Flume">Flume</a>
	<a href="/search?q=云计算">云计算</a>
	<a href="/search?q=ThinkPHP">ThinkPHP</a>
	<a href="/search?q=Python爬虫">Python爬虫</a>
	<a href="/search?q=Coreseek">Coreseek</a>
</div>
</body>
</html>
