
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>中国最大的IT信息搜索引擎</title>
<meta name="keywords" content="中国最大的IT信息搜索引擎" />
<meta name="description" content="中国最大的IT信息搜索引擎" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link type="text/css" rel="stylesheet" href="/static/css/default.css?v=2.2" />
<link rel="shortcut icon" type="image/x-icon" href="/static/img/favicon.ico" />
<link rel="apple-touch-icon" href="/static/img/btbook_apple.jpg" />
</head>
<body>
	<div id="wrapper">
		<div class="top-bar">
			<span class="first"><a href="/">首页</a></span>
			<span><a href="/tags">标签云</a></span> 
			<span><a href="/">视频搜索</a></span> 
			<select autocomplete="off" onchange="changeLanguage(this.value)">
				<option value="CN" selected>简体中文</option>
			</select>
		</div>
		<div id="first-content">
			<div id="center-box-wrapper">
				<div id="center-box">
					<div id="center-logo">
						<a href="/"><img src="/static/img/logo.png"/></a>
					</div>
					<div id="search-box">
						<form id="search-form" action="/search" method="get">
							<input type="text" id="search" name="q" autocomplete="off" placeholder="代码改变世界...." /> 
							<input type="submit" id="btnSearch" value="搜 索" class="blue" />
						</form>
						<div class="info-box" style='display: block;'>
							<ul>
								<li><a href="/search?q=Linux">Linux<i class="new">新</i></a></li>
								<li><a href="/search?q=Nginx">Nginx<i class="new">新</i></a></li>
								<li><a href="/search?q=Mysql">Mysql<i class="new">新</i></a></li>
								<li><a href="/search?q=PHP">PHP<i class="new">新</i></a></li>
								<li><a href="/tags">更多&gt;&gt;</a></li>
							</ul>
							<p style="color: #c0c0c0; margin-top: 10px;">
							     致力于中国最大的IT信息搜索引擎
							</p>
						</div>
					</div>
					<script type="text/javascript">
    				    document.getElementById("search").focus();
    				    document.forms[0].onsubmit = function (e) {
                            e.preventDefault(); 
                            var query = document.getElementById("search").value;
                            if (!query) { document.getElementById("search").focus();
                             return false; 
                             }
                             document.getElementById("search-form").submit();
                        };
                    </script>
				</div>
			</div>
		</div>
		<div class="push"></div>
	</div>
	
	<div class="footer">
		<span>©2016 <a href='http://xiuran.me' target='_blank'>http://xiuran.me</a></span> 
		<span>
			 <a href="javascript:;" rel="nofollow">联系我们</a> 
			| <a href="javascript:;"  rel="nofollow">关于我们</a>
			| <a href="https://github.com/xiaobenxiong/search-web"  rel="nofollow" target='_blank'>源代码</a>
			| <a href="https://github.com/xiaobenxiong/search-crawl"  rel="nofollow" target='_blank'>源代码[爬虫]</a>
		</span>
	</div>
	<script src="/static/js/default.js?v=1" type="text/javascript"></script>

</body>
</html>
